import Head from "next/head";
import Feed from "../Components/Feed";
import Header from "../Components/Header";
import Modal from "../Components/Modal";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FAKEBOOK</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      {/* HEADER */}
      <Header />
      {/* FEED */}
      <Feed />
      {/* MODAL */}
      <Modal />
    </div>
  );
}
